/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PaedagogikRouteImport } from './routes/paedagogik'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as RaeumeRouteImport } from './routes/raeume'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as PaedagogikIndexRouteImport } from './routes/paedagogik/index'
import { Route as PaedagogikAngeboteRouteImport } from './routes/paedagogik/angebote'
import { Route as PaedagogikEssenRouteImport } from './routes/paedagogik/essen'
import { Route as PaedagogikPflegeRouteImport } from './routes/paedagogik/pflege'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PaedagogikRoute = PaedagogikRouteImport.update({
  id: '/paedagogik',
  path: '/paedagogik',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const RaeumeRoute = RaeumeRouteImport.update({
  id: '/raeume',
  path: '/raeume',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const PaedagogikIndexRoute = PaedagogikIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaedagogikRoute,
} as any)
const PaedagogikAngeboteRoute = PaedagogikAngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => PaedagogikRoute,
} as any)
const PaedagogikEssenRoute = PaedagogikEssenRouteImport.update({
  id: '/essen',
  path: '/essen',
  getParentRoute: () => PaedagogikRoute,
} as any)
const PaedagogikPflegeRoute = PaedagogikPflegeRouteImport.update({
  id: '/pflege',
  path: '/pflege',
  getParentRoute: () => PaedagogikRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/paedagogik': typeof PaedagogikRouteWithChildren
  '/preise': typeof PreiseRoute
  '/raeume': typeof RaeumeRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/paedagogik/angebote': typeof PaedagogikAngeboteRoute
  '/paedagogik/essen': typeof PaedagogikEssenRoute
  '/paedagogik/pflege': typeof PaedagogikPflegeRoute
  '/paedagogik/': typeof PaedagogikIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/raeume': typeof RaeumeRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/paedagogik/angebote': typeof PaedagogikAngeboteRoute
  '/paedagogik/essen': typeof PaedagogikEssenRoute
  '/paedagogik/pflege': typeof PaedagogikPflegeRoute
  '/paedagogik': typeof PaedagogikIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/paedagogik': typeof PaedagogikRouteWithChildren
  '/preise': typeof PreiseRoute
  '/raeume': typeof RaeumeRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/paedagogik/angebote': typeof PaedagogikAngeboteRoute
  '/paedagogik/essen': typeof PaedagogikEssenRoute
  '/paedagogik/pflege': typeof PaedagogikPflegeRoute
  '/paedagogik/': typeof PaedagogikIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/paedagogik'
    | '/preise'
    | '/raeume'
    | '/team'
    | '/ueber-uns'
    | '/paedagogik/angebote'
    | '/paedagogik/essen'
    | '/paedagogik/pflege'
    | '/paedagogik/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/preise'
    | '/raeume'
    | '/team'
    | '/ueber-uns'
    | '/paedagogik/angebote'
    | '/paedagogik/essen'
    | '/paedagogik/pflege'
    | '/paedagogik'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/paedagogik'
    | '/preise'
    | '/raeume'
    | '/team'
    | '/ueber-uns'
    | '/paedagogik/angebote'
    | '/paedagogik/essen'
    | '/paedagogik/pflege'
    | '/paedagogik/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PaedagogikRoute: typeof PaedagogikRouteWithChildren
  PreiseRoute: typeof PreiseRoute
  RaeumeRoute: typeof RaeumeRoute
  TeamRoute: typeof TeamRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paedagogik': {
      id: '/paedagogik'
      path: '/paedagogik'
      fullPath: '/paedagogik'
      preLoaderRoute: typeof PaedagogikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raeume': {
      id: '/raeume'
      path: '/raeume'
      fullPath: '/raeume'
      preLoaderRoute: typeof RaeumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paedagogik/': {
      id: '/paedagogik/'
      path: '/'
      fullPath: '/paedagogik/'
      preLoaderRoute: typeof PaedagogikIndexRouteImport
      parentRoute: typeof PaedagogikRoute
    }
    '/paedagogik/angebote': {
      id: '/paedagogik/angebote'
      path: '/angebote'
      fullPath: '/paedagogik/angebote'
      preLoaderRoute: typeof PaedagogikAngeboteRouteImport
      parentRoute: typeof PaedagogikRoute
    }
    '/paedagogik/essen': {
      id: '/paedagogik/essen'
      path: '/essen'
      fullPath: '/paedagogik/essen'
      preLoaderRoute: typeof PaedagogikEssenRouteImport
      parentRoute: typeof PaedagogikRoute
    }
    '/paedagogik/pflege': {
      id: '/paedagogik/pflege'
      path: '/pflege'
      fullPath: '/paedagogik/pflege'
      preLoaderRoute: typeof PaedagogikPflegeRouteImport
      parentRoute: typeof PaedagogikRoute
    }
  }
}

interface PaedagogikRouteChildren {
  PaedagogikAngeboteRoute: typeof PaedagogikAngeboteRoute
  PaedagogikEssenRoute: typeof PaedagogikEssenRoute
  PaedagogikPflegeRoute: typeof PaedagogikPflegeRoute
  PaedagogikIndexRoute: typeof PaedagogikIndexRoute
}

const PaedagogikRouteChildren: PaedagogikRouteChildren = {
  PaedagogikAngeboteRoute: PaedagogikAngeboteRoute,
  PaedagogikEssenRoute: PaedagogikEssenRoute,
  PaedagogikPflegeRoute: PaedagogikPflegeRoute,
  PaedagogikIndexRoute: PaedagogikIndexRoute,
}

const PaedagogikRouteWithChildren = PaedagogikRoute._addFileChildren(
  PaedagogikRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PaedagogikRoute: PaedagogikRouteWithChildren,
  PreiseRoute: PreiseRoute,
  RaeumeRoute: RaeumeRoute,
  TeamRoute: TeamRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
